Country: country
Year: year
Sex: sex
Prevalence_Total: prevalence_total
Prevalence_Male: prevalence_male
Prevalence_Female: prevalence_female
Depression_Prevalence: prevalence_depression
Anxiety_Prevalence: prevalence_anxiety
